name: survival_manual
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/home_background.png
    - assets/fire_starting.gif
    - assets/shelter_building.gif
    - assets/first_aid.gif
    - assets/survive.gif
    - assets/water_purification.gif
    - assets/sur_background.jpg
    - assets/first_aid_intro.jpg
    - assets/first_aiding.jpg
    - assets/interlockfingers_cpr.jpg
    - assets/chest_compressions.gif
    - assets/rescue_breaths.gif
    - assets/check_responsiveness.png
    - assets/heimlich_maneuver.jpg
    - assets/wound_care.jpg
    - assets/tourniquet.gif
    - assets/cleaning_wound.jpg
    - assets/sterile_dressing.jpg
    - assets/fractures_sprains.gif
    - assets/immobilizing_limb.png
    - assets/ice_pack.jpg
    - assets/burn.jpg
    - assets/cool_water.jpg
    - assets/cover_burn.jpg
    - assets/don't_apply.webp
    - assets/hypothermia.gif
    - assets/hypothermia_aid.jpg
    - assets/heat_exhaustion.gif
    - assets/heat_stroke.gif
    - assets/exhaustion_stroke.jpg
    - assets/fire_starting_intro.gif
    - assets/straight_stick.jpg
    - assets/flat_wood.jpg
    - assets/bow.jpg
    - assets/tinder.jpg
    - assets/spin_the_drill.gif
    - assets/transfer_ember.webp
    - assets/stick_wood.webp
    - assets/hand_drill.gif
    - assets/ember_forms.gif
    - assets/flint_and_steel.jpg
    - assets/strike_the_steel.gif
    - assets/water_bottle.png
    - assets/create_lens.png
    - assets/solar_ignition.gif
    - assets/tinder_kindling_fuelwood.jpeg
    - assets/fire_lay.jpg
    - assets/windbreak.jpg
    - assets/fire_starting_last.gif
    - assets/sturdy_branches.jpg
    - assets/small_branches.jpg
    - assets/leaves.jpg
    - assets/ropes.jpg
    - assets/vines.webp
    - assets/long_branch.gif
    - assets/rope_lash_frame.gif
    - assets/short_branch.gif
    - assets/leaves_insulation.gif
    - assets/thick_layer.gif
    - assets/leanto_long_branch.jpg
    - assets/leanto_short_branch.jpg
    - assets/leanto_rocks.png
    - assets/leanto_logs.jpg
    - assets/leanto_support.gif
    - assets/leanto_short_ridgepole.gif
    - assets/leanto_roof.gif
    - assets/aframe_two.jpg
    - assets/aframe_support.gif
    - assets/aframe_short ridgepole.gif
    - assets/aframe_roof.gif
    - assets/bring_the_water.gif
    - assets/boil_water.gif
    - assets/water_filter.gif
    - assets/chemical_treatment.gif
    - assets/dissolve_tablets.gif
    - assets/shake_bottle.gif
    - assets/edible_plants_and_foraging.gif
    - assets/dandelion_leaves.jpg
    - assets/dandelion_flowers.jpg
    - assets/dandelion_roots.jpg
    - assets/wild_blackberries.jpg
    - assets/wild_raspberries.jpeg
    - assets/wild_blueberries.jpg
    - assets/wild_strawberries.jpg
    - assets/garlic_leaves.JPG
    - assets/garlic_bulbs.jpg
    - assets/stinging_nettle_leaves.jpg
    - assets/plantain_leaves.jpg
    - assets/hunting.gif
    - assets/hunting_blind.gif
    - assets/animal_tracks.jpg
    - assets/marksmanship_rifle.jpg
    - assets/marksmanship_bow.jpg
    - assets/marksmanship_slingshot.jpg
    - assets/incision.gif
    - assets/remove_organs.gif
    - assets/butchering.gif
    - assets/trapping.gif
    - assets/deadfall_set_trigger.gif
    - assets/deadfall_secure_weight.gif
    - assets/deadfall_test_trap.gif
    - assets/nylon_cord.webp
    - assets/snare_stick.png
    - assets/nylon_loop.gif
    - assets/snare_trigger.gif
    - assets/snare_test_trap.gif
    - assets/figure4_trap_sticks.jpg
    - assets/figure4_trap_log.jpg
    - assets/figure4_first_stick.gif
    - assets/figure4_second_stick.gif
    - assets/figure4_third_stick.gif
    - assets/figure4_test_trap.gif
    - assets/navigation_techniques.gif
    - assets/compass_housing.jpg
    - assets/bearing.gif
    - assets/interpret_topographic_maps.jpg
    - assets/interpret_topographic_symbols.jpg
    - assets/interpret_topographic_colors.jpg
    - assets/signal_rescue.gif
    - assets/signal_fire.jpg
    - assets/ground_to_air_signals.jpg
    - assets/require_assistance.jpg
    - assets/sos.jpg
    - assets/whistle.gif
    - assets/hold_mirror_eye.gif
    - assets/flash_mirror.gif
    - assets/wildlife_safety.gif
    - assets/binoculars_wild.jpg
    - assets/bear_spray.gif
    - assets/bear_proof.webp
    - assets/leave_no_trace.jpg
    - assets/knot_tying.gif
    - assets/square_knot.jpg
    - assets/clove_hitch.jpg
    - assets/bowline.jpg
    - assets/tautline_hitch.jpg
    - assets/trucker's_hitch.jpg
    - assets/basic_tool_making.gif
    - assets/stone_tools.png
    - assets/bone_knife.jpg
    - assets/wilderness_cooking.gif
    - assets/campfire.jpg
    - assets/direct_cooking.webp
    - assets/indirect_cooking.jpg
    - assets/backpacking_stove.jpeg
    - assets/camp_stove.jpg
    - assets/boiling.jpg
    - assets/simmering.webp
    - assets/frying_pan.jpg
    - assets/weather_forecasting.gif
    - assets/cumulus_cloud.jpg
    - assets/stratus_cloud.jpg
    - assets/cirrus_cloud.webp
    - assets/nimbus_cloud.jpg
    - assets/grass_wind.gif
    - assets/branches_wind.gif
    - assets/windsock.gif
    - assets/barometer.jpg
    - assets/mental_preparedness.gif



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600  
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
